services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3300:3300"  # Le port externe est mappé au port de la gateway
    environment:
      HOST_CUISINE: http://cuisine:3100
      API_KEY_CUISINE: ${API_KEY_CUISINE}
      HOST_DELIVERIES: http://deliveries:3000
      API_KEY_DELIVERIES: ${API_KEY_DELIVERIES}
      HOST_USERS: http://clients:8000
      API_KEY_USERS: ${API_KEY_USERS}
      HOST_ORDERS: http://orders:3200
      API_KEY_ORDERS: ${API_KEY_ORDERS}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - cuisine
      - deliveries
      - orders
      - clients

  cuisine:
    build:
      context: ./srv-cuisine
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY_CUISINE}

  deliveries:
    build:
      context: ./srv-deliveries
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY_DELIVERIES}

  orders:
    build:
      context: ./srv-commandes
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: ${DATABASE_URL}
      API_KEY: ${API_KEY_ORDERS}
  
  clients:
    build:
      context: ./srv-client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Port externe mappé au port interne de clients
    environment:
      SECRET_KEY: ${API_KEY_USERS}
      GATEWAY_URL: "http://gateway:3300"
