services:
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3300:3300"  # Le port externe est mappé au port de la gateway
    env_file:
      - ./gateway/.env
    depends_on:
      - cuisine
      - deliveries
      - clients

  cuisine:
    build:
      context: ./srv-cuisine
      dockerfile: Dockerfile
    ports:
      - "3100:3100"  # Port externe mappé au port interne de cuisine
    env_file:
      - ./srv-cuisine/.env

  deliveries:
    build:
      context: ./srv-deliveries
      dockerfile: Dockerfile
    ports:
      - "3000:3000"  # Port externe mappé au port interne de deliveries
    env_file:
      - ./srv-deliveries/.env
  
  clients:
    build:
      context: ./srv-client
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Port externe mappé au port interne de clients
    env_file:
      - ./srv-client/.env